# Generated by Django 3.2.9 on 2021-12-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Insira seu e-mail')),
                ('telefone', models.CharField(max_length=16, verbose_name='Insira seu telefone')),
                ('mensagem', models.TextField(max_length=300, verbose_name='Deixe sua mensagem ...')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
