# Generated by Django 3.2.9 on 2021-12-03 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_cliente_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('peso', models.BooleanField(default=False)),
                ('categoria', models.CharField(blank=True, choices=[('Ca', 'Cachorro'), ('Ga', 'Gato'), ('Pa', 'Pássaro'), ('Ha', 'Hamister')], max_length=2, null=True)),
                ('cor', models.CharField(blank=True, choices=[('Pr', 'Preto'), ('Br', 'Branco'), ('Ci', 'Cinza'), ('Ma', 'Malhado'), ('Cr', 'Creme'), ('Mr', 'Marrom'), ('Am', 'Amarelo')], max_length=2, null=True)),
                ('raca', models.TextField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Fe', 'Femea'), ('Ma', 'Macho')], max_length=2, null=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_app.cliente')),
            ],
        ),
    ]
